version: "3.8"
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432  
    env_file:
      - ./app/.env

  foodgram:
    build: .
    expose:
      - 8010
    depends_on:
      - db
    env_file:
      - ./app/.env
    volumes:
      - ./code/app/static
      - ./code/app/media

  nginx:
    restart: always
    build: ./nginx    
    ports:
      - 8000:80
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./code/app/static
      - ./code/app/media
    depends_on:
      - foodgram

volumes:
  postgres_data: