# Generated by Django 3.1 on 2020-11-19 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredients',
            options={'verbose_name': 'Дозировка', 'verbose_name_plural': 'Дозировка'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['title'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['pk'], 'verbose_name': 'Время', 'verbose_name_plural': 'Время'},
        ),
        migrations.AlterField(
            model_name='amountingredients',
            name='amount',
            field=models.IntegerField(verbose_name='Дозировка'),
        ),
        migrations.AlterField(
            model_name='amountingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipe.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='time',
            name='reduction',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='time',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
