# Generated by Django 3.1 on 2020-11-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20201119_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredients',
            options={'ordering': ['recipe', 'pk'], 'verbose_name': 'Дозировка', 'verbose_name_plural': 'Дозировка'},
        ),
        migrations.AlterField(
            model_name='amountingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Блюдо'),
        ),
    ]
